
  # Step 3: Deploy to Cloud Run with the required settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'agent-ops',
        '--image=asia-south1-docker.pkg.dev/gen-lang-client-0206046645/cloud-run-source-deploy/agent_ops/agent-ops:$COMMIT_SHA',
        '--region=asia-south1',
        '--platform=managed',
        '--service-account=911008082076-compute@developer.gserviceaccount.com',
        '--concurrency=80',
        '--timeout=300',
        '--max-instances=20',
        '--cpu=1',
        '--memory=512Mi',
        '--port=8080',
        '--allow-unauthenticated'
      ]

images:
  - 'asia-south1-docker.pkg.dev/gen-lang-client-0206046645/cloud-run-source-deploy/agent_ops/agent-ops:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
