apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: agent-ops
  namespace: '911008082076'
  selfLink: /apis/serving.knative.dev/v1/namespaces/911008082076/services/agent-ops
  uid: a335d1a6-2bc7-4d39-9290-eb91984b45ed
  resourceVersion: AAY326l5ngQ
  generation: 2
  creationTimestamp: '2025-06-18T17:07:11.122462Z'
  labels:
    gcb-trigger-id: f3ae635c-5f68-489b-a93c-81d5341e3aaf
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-region: global
    run.googleapis.com/satisfiesPzs: 'true'
    cloud.googleapis.com/location: asia-south1
  annotations:
    serving.knative.dev/creator: vikalp.dongre@gmail.com
    serving.knative.dev/lastModifier: vikalp.dongre@gmail.com
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/operation-id: 143059b1-c0b0-48a9-86f4-b28fcb3f2d58
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '1'
    run.googleapis.com/urls: '["https://agent-ops-911008082076.asia-south1.run.app","https://agent-ops-54lib5iv4a-el.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 911008082076-compute@developer.gserviceaccount.com
      containers:
      - name: placeholder-1
        image: gcr.io/cloudrun/placeholder
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 2
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2025-06-18T17:07:20.949252Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2025-06-18T17:07:19.666503Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2025-06-18T17:07:20.913710Z'
  latestReadyRevisionName: agent-ops-00001-kc9
  latestCreatedRevisionName: agent-ops-00001-kc9
  traffic:
  - revisionName: agent-ops-00001-kc9
    percent: 100
    latestRevision: true
  url: https://agent-ops-54lib5iv4a-el.a.run.app
  address:
    url: https://agent-ops-54lib5iv4a-el.a.run.app
